### ISSUE TITLE
ImportError: No module named 'oscar_accounts'

### ISSUE THREAD

**Issue by yatahaze** [django-oscar/django-oscar-accounts#47]
Installed this as per the docs. I get this error. 

pip install django-oscar-accounts
<add oscar_accounts to the apps>
python manage.py migrate oscar_accounts

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ryan/apps/oscar/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/ryan/apps/oscar/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/ryan/apps/oscar/venv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ryan/apps/oscar/venv/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ryan/apps/oscar/venv/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/ryan/apps/oscar/venv/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'oscar_accounts'
```

**Comment by yatahaze** [comment]
Update: pip installed the wrong version on me, fixed it with ```pip install django-oscar-accounts==0.4rc1 --upgrade```

**Comment by SalahAdDin** [comment]
So, what's about `django-oscar-accoutns` new release version?
