### ISSUE TITLE
import url error.

### ISSUE THREAD

**Issue by prince-tanapong** [django-oscar/django-oscar-accounts#54]
Got this error when try to add to urls.py with django 1.11.5

root@661e03d02baa:/application# python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7faf22e140d0>
Traceback (most recent call last):
  File "/appenv/lib/python3.4/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/appenv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/appenv/lib/python3.4/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/appenv/lib/python3.4/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/appenv/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/appenv/lib/python3.4/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/appenv/lib/python3.4/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/appenv/lib/python3.4/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/appenv/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/appenv/lib/python3.4/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/appenv/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/appenv/lib/python3.4/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/appenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/application/oscar_phenom_health/urls.py", line 24, in <module>
    from oscar_accounts.dashboard.app import application as accounts_app
  File "/appenv/lib/python3.4/site-packages/oscar_accounts/dashboard/app.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns

**Comment by solarissmoke** [comment]
This was fixed in e12c38a73e70434a0dd3f65fdffbd8ead3808ccf . Please use the latest package from Github, as an update hasn't been released on Pypi yet.
